### ISSUE TITLE
Adopt 'CERN OHL W 2.0' licence for hardware design

### ISSUE THREAD

**Issue by simonsan** [SamuelNoesslboeck/SyArm_Mk1#6]
## Introduction
CERN has developed the CERN Open Hardware Licence (CERN OHL) as a legal tool to promote collaboration among hardware designers and support the freedom to use, study, modify, share and distribute hardware designs, and products based on those designs.

## Why not use existing licences such as GPL and any in the family of Creative Commons licences?

>  The CERN OHL was drafted with hardware in mind. The fact that the licensed materials are going to take part in the process of creating hardware has various implications. For example, the presence of patents is more pervasive in the hardware world than in software or in works of art. The CERN OHL appropriately has a patent licensing section, which is lacking for example in CC licences. What does this mean in practice? If I release a design for which I hold patents under, say, CC-BY-SA, and you take it and use it, e.g. to build hardware and commercialise it, I can sue you for patent infringement. The CERN OHL v2 contains a patent licence, i.e. a promise of the licensor to all potential licensees that they can use the design without fear of being sued for patent infringement in that design by the licensor. The CERN OHL v2 also contains a patent retaliation clause: licensees who sue the licensor for patent infringement automatically lose their rights under the licence.

> The realities of hardware design in terms of design tools are also very different from those of software. It is for example very common to design Application Specific Integrated Circuits (ASICs) using proprietary tools with proprietary libraries which are an integral part of the final design. Something similar happens with the design of Field Programmable Gate Arrays (FPGAs). PCB design is also often done using proprietary tools. These realities need to be taken into account in the drafting of the licence if we don't want a strongly reciprocal licence which can only apply in an extremely reduced number of cases.

> Finally, it is important for a licence to contain text that practitioners can easily relate to. The CERN OHL strives to use clear terms and definitions that have easily recognisable and intuitive meanings for hardware designers.

src.: https://ohwr.org/project/cernohl/wikis/faq#q-why-not-use-existing-licences-such-as-gpl-and-any-in-the-family-of-creative-commons-licences

## [Licence overview](https://cern-ohl.web.cern.ch/)

# [Proposed licence](https://ohwr.org/cern_ohl_w_v2.txt)

**Comment by SamuelNoesslboeck** [comment]
Thanks a lot!
